### ISSUE TITLE
ベースモデル作成

### ISSUE THREAD

**Issue by yusaku-uchii** [Kunihiro-ikd/signate_moving#14]
2011年4月1日からのデータを用いてください

**Comment by ayukichi** [comment]
#16
修正版マージしておきました！
最終行にて、訓練データと検証データそれぞれに対してのMAEも出しておきました。

**TimeSeriesSplit**については、tensorflowに引数がないようですが、
**model.fit**の引数にて、
`validation_data = [val_x, val_y]`と指定しておけば、validation_splitと違ってシャッフルすることなく、
一つのvalidation_dataを使ってval_lossを出すことができます！
